hardware_control_loop:
  loop_hz: 1000

# Settings for ros_control hardware interface
ur_hardware_interface:
  joints: &robot_joints
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

ur5e_cartesian_velocity_controller_pid:
  type: cartesian_controller/CartesianVelocityControllerPID
  publish_rate: 1000
  root_name: base_link_inertia
  tip_name: wrist_3_link

ur5e_cartesian_velocity_controller_pid_sim:
  type: cartesian_controller/CartesianVelocityControllerPIDSim
  publish_rate: 1000
  root_name: base_link_inertia
  tip_name: wrist_3_link

ur5e_cartesian_state_controller:
    type: cartesian_controller/CartesianStateController
    publish_rate: 1000
    root_name: base_link_inertia
    tip_name: wrist_3_link

#Publish wrench ----------------------------------
force_torque_sensor_controller:
    type: force_torque_sensor_controller/ForceTorqueSensorController
    publish_rate: 1000
