ur5e:
  # Controller for the real hardware (velocity interface)
  cartesian_velocity_controller_pid:
    type: cartesian_controller/CartesianVelocityControllerPID
    publish_rate: 1000
    root_name: base_link
    tip_name: ee_link

  # Controller for gazebo (velocity interface on top of a position interface)
  cartesian_velocity_controller_pid_sim:
    type: cartesian_controller/CartesianVelocityControllerPIDSim
    publish_rate: 1000
    root_name: base_link
    tip_name: ee_link

  cartesian_velocity_controller_adm:
    type: cartesian_controller/CartesianVelocityControllerADM
    publish_rate: 1000
    root_name: base_link
    tip_name: ee_link

  # Controller for gazebo (velocity interface on top of a position interface)
  cartesian_velocity_controller_adm_sim:
    type: cartesian_controller/CartesianVelocityControllerADMSim
    publish_rate: 1000
    root_name: base_link
    tip_name: ee_link
       
  cartesian_position_controller:
    type: cartesian_controller/CartesianPositionController
    publish_rate: 1000
    root_name: base_link
    tip_name: ee_link

  cartesian_position_controller_sim:
    type: cartesian_controller/CartesianPositionControllerSim
    publish_rate: 1000
    root_name: base_link
    tip_name: ee_link

  # Cartesian state publisher
  cartesian_state_controller:
    type: cartesian_controller/CartesianStateController
    publish_rate: 1000
    root_name: base_link
    tip_name: ee_link
